package com.csis3275.automated_blackbox_test_epe_07;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EmailTestmjo56Test {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
	System.setProperty("webdriver.chrome.drive", "C:/temp/chromedriver.exe");
 driver = new ChromeDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void emailTestmjo56() {
 driver.get("http://localhost:8080/StrugglingDevelopers_RoomBookingSystem/");
 driver.manage().window().setSize(new Dimension(968, 1040));
 driver.findElement(By.linkText("Login")).click();
 driver.findElement(By.id("email")).click();
 driver.findElement(By.id("email")).sendKeys("etakisa@shutterfly.com");
 driver.findElement(By.id("password")).click();
 driver.findElement(By.id("password")).sendKeys("NBDhya6k");
 driver.findElement(By.cssSelector(".btn")).click();
 driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
 driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link")).click();
 driver.findElement(By.id("title")).click();
 {
   WebElement dropdown = driver.findElement(By.id("title"));
   dropdown.findElement(By.xpath("//option[. = 'Meeting']")).click();
 }
 driver.findElement(By.id("title")).click();
 driver.findElement(By.id("description")).click();
 driver.findElement(By.id("description")).sendKeys("Meeting");
 driver.findElement(By.id("room_id")).click();
 driver.findElement(By.id("room_id")).sendKeys("D0068");
 driver.findElement(By.id("dateTime")).click();
 driver.findElement(By.id("dateTime")).sendKeys("2020-12-16");
 driver.findElement(By.id("startTime")).click();
 driver.findElement(By.id("startTime")).sendKeys("13:25");
 driver.findElement(By.id("endTime")).click();
 driver.findElement(By.id("endTime")).sendKeys("14:25");
 driver.findElement(By.id("endTime")).click();
 driver.findElement(By.id("booking")).click();
 driver.findElement(By.cssSelector(".btn")).click();
 driver.findElement(By.cssSelector(".col-md-offset-3:nth-child(4) > .btn")).click();
 driver.findElement(By.name("email")).click();
 driver.findElement(By.name("email")).sendKeys("joshimansi224@gmail.com");
 driver.findElement(By.cssSelector("input:nth-child(3)")).click();
}
}

